# Generated by Django 6.0.3 on 2026-04-04 00:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('spaces', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('serie', models.CharField(blank=True, max_length=10)),
                ('numero', models.CharField(blank=True, max_length=20)),
                ('data_emissao', models.DateTimeField(blank=True, null=True)),
                ('valor_total', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('emitente_nome', models.CharField(blank=True, max_length=255)),
                ('emitente_cnpj', models.CharField(blank=True, max_length=18)),
                ('emitente_endereco', models.CharField(blank=True, max_length=255)),
                ('emitente_municipio', models.CharField(blank=True, max_length=100)),
                ('emitente_uf', models.CharField(blank=True, max_length=2)),
                ('destinatario_nome', models.CharField(blank=True, max_length=255)),
                ('destinatario_cnpj', models.CharField(blank=True, max_length=18)),
                ('destinatario_cpf', models.CharField(blank=True, max_length=14)),
                ('valor_total_produtos', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('valor_total_descontos', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('valor_pis', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('valor_cofins', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('valor_aproximado_tributos', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('meio_pagamento', models.CharField(blank=True, max_length=50)),
                ('valor_pagamento', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='spaces.space')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-data_emissao'],
            },
        ),
        migrations.CreateModel(
            name='ReceiptItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('numero', models.CharField(blank=True, max_length=10)),
                ('descricao', models.CharField(blank=True, max_length=255)),
                ('quantidade', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('unidade_comercial', models.CharField(blank=True, max_length=10)),
                ('valor', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('cfop', models.CharField(blank=True, max_length=4)),
                ('valor_aproximado_tributos', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='receipts.receipt')),
            ],
            options={
                'ordering': ['numero'],
            },
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('cnpj', models.CharField(blank=True, db_index=True, max_length=18)),
                ('nome', models.CharField(blank=True, max_length=255)),
                ('inscricao_estadual', models.CharField(blank=True, max_length=20)),
                ('telefone', models.CharField(blank=True, max_length=20)),
                ('endereco', models.CharField(blank=True, max_length=255)),
                ('bairro', models.CharField(blank=True, max_length=100)),
                ('cep', models.CharField(blank=True, max_length=10)),
                ('municipio', models.CharField(blank=True, max_length=100)),
                ('uf', models.CharField(blank=True, max_length=2)),
                ('pais', models.CharField(blank=True, max_length=100)),
                ('space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stores', to='spaces.space')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['nome', 'municipio'],
            },
        ),
        migrations.AddField(
            model_name='receipt',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receipts', to='receipts.store'),
        ),
    ]
