# Generated by Django 6.0.3 on 2026-04-04 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0002_alter_receipt_destinatario_cnpj_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='url',
            field=models.URLField(blank=True, max_length=500, null=True, unique=True),
        ),
    ]
