# Generated by Django 6.0.3 on 2026-03-18 23:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('spaces', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATE', 'Criação'), ('UPDATE', 'Edição'), ('DELETE', 'Exclusão'), ('SOFT_DELETE', 'Exclusão Lógica'), ('VIEW', 'Visualização'), ('LOGIN', 'Login'), ('INVITE', 'Convite'), ('JOIN', 'Entrada'), ('LEAVE', 'Saída')], max_length=20)),
                ('model_name', models.CharField(max_length=50)),
                ('object_id', models.PositiveIntegerField()),
                ('object_repr', models.CharField(blank=True, max_length=200)),
                ('old_data', models.JSONField(blank=True, default=dict)),
                ('new_data', models.JSONField(blank=True, default=dict)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('space', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='spaces.space')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['model_name', 'object_id'], name='core_auditl_model_n_3fb686_idx'), models.Index(fields=['user', '-created_at'], name='core_auditl_user_id_969660_idx'), models.Index(fields=['space', '-created_at'], name='core_auditl_space_i_eb1618_idx'), models.Index(fields=['action', '-created_at'], name='core_auditl_action_d80c2d_idx')],
            },
        ),
    ]
